// JavaScript Document

/*
<a id="template-list" href="#">All My Templates | <span class="newItem">New Item Added</span></a>
<div id="container">
<ul>
<li><a class="screenshot" rev="http://digith.net/demo/images/belega.jpg" href="http://digith.net/belega/belega/digith_template_builder/" rel="CreativeMail" goumai="http://digith.net/belega/belega/digith_template_builder/123"><span class="id newItem">BELEGA Responsive Mail</span><span class="category newLab">New!</span></a></li>
<li><a class="screenshot" rev="http://digith.net/demo/images/MiniShow.jpg" href="http://digith.net/minishow/minishow/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"><span class="id upItem">Minishow Responsive Mail</span><span class="category upLab">Updated</span></a></li>
<li><a class="screenshot" rev="http://digith.net/demo/images/ballio.jpg" href="http://digith.net/ballio/ballio/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"> <span class="id">BALLIO Responsive Mail With Builder</span></a></li>
<li><a class="screenshot" rev="http://digith.net/demo/images/flata.jpg"  href="http://digith.net/flata/flata/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"> <span class="id">FLATA Responsive Mail With Builder</span></a></li>
<li><a class="screenshot" rev="http://digith.net/demo/images/conny3.jpg" href="http://digith.net/conny3/conny3/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"> <span class="id">CONNY3 Responsive Mail With Builder</span></a></li>
<li><a class="screenshot" rev="http://digith.net/demo/images/metrola.jpg" href="http://digith.net/metrola/metrola/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"> <span class="id">MetroLa Responsive Mail With Builder</span></a></li>
</ul>
</div>
*/


var		myItem = 
'<a id="template-list" href="#">All My Templates | <span class="newItem">New Item Added</span></a><div id="container"><ul><li><a class="screenshot" rev="http://digith.net/demo/images/belega.jpg" href="http://digith.net/belega/belega/digith_template_builder/" rel="CreativeMail" goumai="http://digith.net/belega/belega/digith_template_builder/123"><span class="id newItem">BELEGA Responsive Mail</span><span class="category newLab">New!</span></a></li><li><a class="screenshot" rev="http://digith.net/demo/images/MiniShow.jpg" href="http://digith.net/minishow/minishow/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"><span class="id upItem">Minishow Responsive Mail</span><span class="category upLab">Updated</span></a></li><li><a class="screenshot" rev="http://digith.net/demo/images/ballio.jpg" href="http://digith.net/ballio/ballio/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"> <span class="id">BALLIO Responsive Mail With Builder</span></a></li><li><a class="screenshot" rev="http://digith.net/demo/images/flata.jpg" href="http://digith.net/flata/flata/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"> <span class="id">FLATA Responsive Mail With Builder</span></a></li><li><a class="screenshot" rev="http://digith.net/demo/images/conny3.jpg" href="http://digith.net/conny3/conny3/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"> <span class="id">CONNY3 Responsive Mail With Builder</span></a></li><li><a class="screenshot" rev="http://digith.net/demo/images/metrola.jpg" href="http://digith.net/metrola/metrola/digith_template_builder/" rel="Minishow" goumai="http://digith.net/belega/belega/digith_template_builder/123"> <span class="id">MetroLa Responsive Mail With Builder</span></a></li></ul></div>',

		guideInfo = "Hi, Minishow updated, if you purchased it, please redownload the main file, thanks!";