/*

 Template Builder v 2.6
 (2.6.0 - by revaxarts)

 Copyright (c) 2013 Xaver Birsak
 http://rxa.li/themeforest

 Licensed under the Envato Pty Ltd License Terms:
 http://themeforest.net/wiki/support/legal-terms/licensing-terms/

 limited, non-exclusive, non-transferable, non-sublicensable license
*/
$(document).ready(function(){var R=function(S){function J(){var a=location.pathname.split("/");a.pop();a.pop();m=location.protocol+"//"+location.host+a.join("/")+"/version"+b.version+"/img/"}function z(a){b.elements=$.map(h.find("img"),function(a,d){return $(a).attr("alt")});b.preheader=A.val();b.inline=s.is(":checked");b.absoluteurls=l.is(":checked");b.imagepath=v.val();b.color=B.val();b.service?(b.apikey=$("#"+b.service+"_apikey").val(),b.templatename=$("#"+b.service+"_templatename").val()):b.apikey=
b.templatename=null;b.useeditor="cm"==b.service?$("#cm_useeditor").is(":checked"):null;K.is(":checked")&&(savestring=b.serialize());a&&"object"==typeof JSON&&(a=b,delete a.elements,localStorage.setItem(location.pathname+"settings",JSON.stringify(a)),k("settings saved!"));var d="";$.each(b,function(a,b){switch(a){case "elements":(b=b.length)||(b='<span style="color:#f00;">no elements defined!</span>');break;case "clientid":b=$("option[value="+b+"]").html();a="client";break;case "service":b="cm"==b?
"Campaign Monitor":"mc"==b?"Mailchimp":"None";break;case "color":b='<span style="background-color:#'+b+'">&nbsp;</span>'+b}null!==b&&(d+="<dt>"+a+"</dt><dd>"+b+"</dd>")});$("#summery").html(d)}function t(){h.find("li").length?h.addClass("items"):h.removeClass("items")}function C(){if("object"===typeof prebuilds){w.html("");var a=D(),d="";$.isEmptyObject(a)||(d+='<h3>Custom</h3><ul class="prebuilds">',$.each(a,function(a,b){d+='<li><a name="'+a+'" class="prebuild">'+a+'</a><a class="delete">&times;</a></li>'}),
d+="</ul>");d+='<h3>Prebuilds</h3><ul class="prebuilds">';$.each(prebuilds,function(a,b){d+='<li><a name="'+a+'" class="prebuild">'+a+"</a></li>"});d+='</ul><ul id="preview"></ul>';w.html(d);E=$.extend({},prebuilds,a);u=$("#preview")}else throw"no prebuilds set";}function F(a){$('<li><a class="delete" title="delete">&times;</a><img src="../_img/types/'+a+'.gif" width="98" alt="'+a+'" title="'+elements[a]+'"></li>').hide().appendTo(h).slideDown()}function x(a,d){p!=a?$("section").eq(p).fadeOut(200,
function(){$("section").eq(a).fadeIn(200,function(){L(a);$.isFunction(d)&&d()})}):($("section").eq(a).fadeIn(),L(a),$.isFunction(d)&&d());$("nav").find("a").removeClass("active").eq(a).addClass("active");$("#progress").animate({width:0==a?75:1==a?195:315},300*Math.abs(p-a));p=a}function L(a){z();switch(a){case 2:M()}}function M(a){if(g())return!1;g(!0);a=a||"../version"+b.version+"/all"+(b.inline?"_inline":"")+(b.service?"_"+b.service:"")+".html";n.val("loading HTML...");$.ajax({url:a,success:function(a){if("cm"==
b.service&&b.useeditor){for(var c=[],f=b.elements.length-1;0<=f;f--){var e=b.elements[f];-1===$.inArray(e,c)&&c.unshift(e)}b.elements=c}a=(new T(a)).get(b.absoluteurls,b.useeditor,b.imagepath);n.val(a);g(!1);k("HTML loaded!",!0);q=0},error:function(a,c,f){g(!1);3>q?(q?k("couldn't load HTML ... load example (attempt "+(q+1)+")",!1):k("couldn't load HTML ... load example",!1),q++,setTimeout(function(){M("proxy.php?method=examplehtml&color="+b.color)},1E3)):(alert("Unable to generate HTML!\nPlease make sure you've uploaded all files correctly!"),
q=0)},dataType:"html"})}function g(a){if("undefined"==typeof a)return!!G;a?G++:G--;g()?N.addClass("busy"):N.removeClass("busy")}function k(a,d){$("<div>",{"class":"msg"}).addClass(!0===d?"success":!1===d?"error":"").hide().html(a).prependTo(U).slideDown().delay(!1===d?9E3:5E3).fadeOut(function(){$(this).remove()})}function H(){h.find("li").slideUp(function(){$(this).remove()})}function V(a,d){var c="undefined"!=typeof window.screenX?window.screenX:window.screenLeft,b="undefined"!=typeof window.screenY?
window.screenY:window.screenTop,e="undefined"!=typeof window.outerHeight?window.outerHeight:document.documentElement.clientHeight-22,c=parseInt((0>c?window.screen.width+c:c)+(("undefined"!=typeof window.outerWidth?window.outerWidth:document.documentElement.clientWidth)-a)/2,10),b=parseInt(b+(e-d)/2.5,10);return"width="+a+",height="+d+",left="+c+",top="+b+",scrollbars=1"}function r(a,d,c,b){$.post("proxy.php",$.extend(d,{method:a}),function(a){$.isFunction(c)&&c(a);!a.success&&$.isFunction(b)&&b(a);
k(a.response,a.success)},"json")}function W(a){var d=D();delete d[a];O(d)}function O(a){a=$.map(a,function(a,b){return b+":"+a.join(",")});P("CustomLayouts",a.join("|"))}function D(){var a=Q("CustomLayouts");if(a){for(var a=a.split("|"),d={},b,f=a.length-1;0<=f;f--)b=a[f].split(":"),d[b[0]]=b[1].split(",");return d}return{}}function P(a,b,c){var f=new Date;c=c||31536E6;f=new Date(f.getTime()+c);document.cookie=a+"="+b+"; expires="+f.toGMTString()+"; "}function Q(a){for(var b=document.cookie.split(";"),
c,f=0;f<b.length;f++)if(c=b[f].substring(b[f].search("=")+1),a==$.trim(b[f].substring(0,b[f].search("="))))return c;return!1}if(this===window)return new R(S);var p=0,q=0,m,E,G=0,b={version:1,color:null,elements:[],service:null,apikey:null,clientid:null,templatename:null,inline:!0,imagepath:null,absoluteurls:!0,useeditor:!1},u,n=$("#output"),U=$("#status"),N=$("#content"),h=$("#dropzone"),w=$("#prebuilds"),y=$("#versions"),I=$("#services"),K=$("#savesettings"),s=$("#inlinecss"),A=$("#preheader"),l=
$("#absoluteurls"),v=$("#domain"),B=$("#customcolor"),T=function(a){function d(){var d="";$.each(b.elements,function(b,g){var k=d;f=RegExp("(\x3c!-- [^"+c+"]+)"+c+""+g+""+c+" --\x3e([^"+c+"]+)"+c+""+g+""+c+"([^<]+)","g");e=f.exec(a);d=k+(e?e[1]+" --\x3e"+e[2]+" "+e[3]:"")});return d}var c="\u263a",f,e;return{get:function(g,k,h){var l;l="";f=RegExp("([^"+c+"]+)[^>]+ --\x3e","gi");e=f.exec(a);l+=e?e[0]+"\n":"";l+=d();f=RegExp("\x3c!-- Footer start --\x3e([^"+c+"]+)","gi");e=f.exec(a);e=(l+=e?"\x3c!-- Footer start --\x3e"+
e[1]:"")||a;g&&(e=e.replace(/src="img\//g,'src="'+(h||m)).replace(/background="img\//g,'background="'+(h||m)).replace(/url\('img\//g,"url('"+(h||m)));e=e.replace("\x3c!-- PREHEADER --\x3e",A.val()||"");switch(b.service){case "mc":g=/mc:edit="([^"]+)"/gi;for(h={};result=g.exec(e);)h[result[1]]?e=e.replace(result[0],'mc:edit="'+result[1]+" ("+h[result[1]]++ +')"'):(h[result[1]]=1,e=e.replace(result[0],'mc:edit="'+result[1]+'%%%%"'));e=e.replace(/%%%%"/g,'"');break;case "cm":g=/label="([^"]+)"/gi;for(h=
{};result=g.exec(e);)h[result[1]]?e=e.replace(result[0],'label="'+result[1]+" ("+h[result[1]]++ +')"'):(h[result[1]]=1,e=e.replace(result[0],'label="'+result[1]+'%%%%"'));e=e.replace(/%%%%"/g,'"');!1===k&&(e=e.replace(/<\/?repeater>/gi,"").replace(/<\/?layout([^>]*)>/gi,""))}return e=e.replace(RegExp("#"+colors[b.version-1],"g"),"#"+b.color)}}};(function(){var a=Q("lastservercheck"),b=(new Date).getTime(),c;180<=(b-a)/6E4&&(c=setTimeout(function(){confirm("No response from the server! Would you like to check the configuration?")?
location.href="proxy.php":alert("The Template Builder may not work as expected with your current server configuration!")},5E3),k("checking server configuration..."),r("check",null,function(a){if(null===a)return!1;clearTimeout(c);P("lastservercheck",b);a&&a.success||setTimeout(function(){confirm("It seems your server needs an update:\n\n"+a.response.replace(/<br>/g,"\n")+"\nWould you like to check the configuration?")?location.href="proxy.php":alert("The Template Builder may not work as expected with your current server configuration!")},
1E3)}))})();C();(function(){if("object"===typeof elements){var a=0,b=0;$.each(elements,function(b,d){a++});var c="<ul>";$.each(elements,function(f,e){b++;c+='<li><img src="../_img/types/'+f+'.gif" width="98" alt="'+f+'" title="'+e+'"></li>';parseInt(b%(a/4),10)||(c+="</ul><ul>")});c+="</ul>";$("#elements").html(c).find("img").css({opacity:0.8})}else throw"no elements set";})();(function(){$("#elements ul li").draggable({connectToSortable:h,containment:"#content",helper:"clone",revert:"invalid",zIndex:1E3});
h.sortable({stop:function(a,b){b.offset.left>h.offset().left+110&&b.item.find("a.delete").click()},receive:function(a,b){h.find("li").each(function(){var a=$(this);a.has("a").length||(a.find("img").css("opacity",1),$('<a class="delete" title="delete">&times;</a>').prependTo(a))});t()},containment:"#rec",revert:!0,distance:10,revertDuration:1})})();(function(){if("object"===typeof colors){for(var a="<ul>",b=colors.length,c=0;c<b;c++)a+='<li style="background-color:#'+bgcolors[c]+'"><a title="color #'+
colors[c]+'" style="background-color:#'+colors[c]+'" data-color="#'+colors[c]+'" data-version="'+(c+1)+'"></a></li>';y.html(a+"</ul>")}else throw"no prebuilds set";})();(function(){$("body").delegate("a[href^='http']","click",function(){window.open($(this).attr("href"));return!1});$("nav").delegate("a","click",function(){var a=$(this);x(a.data("id"),function(){});return!1});$(".next").bind("click",function(){x(p+1)});$(".prev").bind("click",function(){x(p-1)});w.delegate("a.delete","click",function(){var a=
$(this);W(a.prev().attr("name"));a.parent().slideUp(function(){C()})}).delegate("a.prebuild","click",function(){H();$.each(E[this.name],function(a,b){F(b)});t()}).delegate("a.prebuild","mouseenter",function(){var a="";$.each(E[this.name],function(b,c){a+='<li><img src="../_img/types/'+c+'.gif" width="98" alt="'+c+'" title="'+name+'"></li>'});u.css({left:w.position().left+200});u.html(a).stop().fadeTo(100,1)}).delegate("a.prebuild","mouseleave",function(){u.stop().fadeOut(100)}).bind("mousemove",function(a){u.css({top:a.pageY-
120})});$("#elements").find("img").bind({click:function(){F(this.alt);t();k('added module "'+elements[this.alt]+'"')},mouseover:function(){$(this).stop().fadeTo(100,1)},mouseout:function(){$(this).stop().fadeTo(100,0.8)}});$("#cleardz").bind("click",function(){H();h.removeClass("items")});$("#savelayout").bind("click",function(){z();if(!b.elements.length)return k("Please bring some elements in the dropzone!"),!1;if(name=prompt("Save your layout for later!\nYou have to define a name. If the name already exists it will get overwritten")){var a=
name,d=b.elements,c=D();c[a]=d;O(c);C()}});$("#addAll").bind("click",function(){H();$.each($("#elements").find("img"),function(a,b){F(this.alt)});t()});h.delegate("a.delete","click",function(){$(this).parent().slideUp(function(){$(this).remove();t()})});y.delegate("li","click",function(){var a=$(this).find("a");b.version=a.data("version");b.color=a.data("color");B.val(b.color.substr(1)).css("background-color",b.color).trigger("change");y.find(".active").removeClass("active");$(this).addClass("active");
J();l.trigger("change")});I.delegate("a[data-role]","click",function(){var a=$(this);if(!a.data("role")||a.next().is(":hidden"))I.find(".active").removeClass("active"),I.find(".service").slideUp();b.service=a.data("role");a.next().slideDown().find("input").eq(0).focus();switch(a.data("role")){case "mc":$("#cm_upload").hide();s.prop("checked",!1).prop("disabled",!0);l.prop("checked",!0).prop("disabled",!0).trigger("change");break;case "cm":$("#mc_upload").hide();s.prop("checked",!1).prop("disabled",
!0);l.prop("checked",!0).prop("disabled",!0).trigger("change");break;default:l.prop("disabled",!1),s.prop("disabled",!1),$("#cm_upload").hide(),$("#mc_upload").hide()}a.addClass("active")}).delegate("#mc_apikey","change",function(){var a=$(this),d={apikey:a.eq(0).val()};if(g()||!d.apikey)return!1;g(!0);a.removeClass("error success").addClass("loading");k("verifying api key...");r("ping_mc",d,function(c){a.removeClass("loading error success").addClass(c.success?"success":"error");g(!1);b.clientid=
null;c.success?($("#mc_upload").show(),b.apikey=d.apikey):($("#mc_upload").hide(),b.apikey=null)})}).delegate("#cm_apikey","change",function(){var a=$(this),d={apikey:a.eq(0).val()};if(g()||!d.apikey)return!1;g(!0);a.removeClass("error success").addClass("loading");k("verifying credentials...");r("ping_cm",d,function(c){a.removeClass("loading error success").addClass(c.success?"success":"error");g(!1);c.success?(clients=$.map(c.clients,function(a,c){return'<option value="'+a.ClientID+'"'+(b.clientid==
a.ClientID?" selected":"")+">"+a.Name+"</option>"}),$("#cm_clientid").prop("disabled",!1).html(clients.join("")),b.clientid||$("#cm_clientid").find("option").eq(0).attr("selected","selected"),b.clientid=$("#cm_clientid").find("option:selected").val(),b.apikey=d.apikey,$("#cm_upload").show()):($("#cm_upload").hide(),b.clientid=null,b.apikey=null)})}).delegate("#cm_clientid","change",function(){b.clientid=$(this).val()}).delegate("a.btn","click",function(){$(this).parent().parent().find(".input").eq(0).trigger("change")});
l.bind("change",function(){l.is(":checked")?v.val(m):v.val("")});K.bind("click",function(){z(!0)});$("#clearsettings").bind("click",function(){k("clear settings...");localStorage.removeItem(location.pathname+"settings");k("cleared!")});$("#previewbtn").bind("click",function(){var a=window.open("about:blank","preview",V(640,900));a.document.body.innerHTML='<span style="font-family:sans-serif">please wait...</span>';setTimeout(function(){var b=n.val(),b=b.replace(/src="img\//g,'src="'+m).replace(/background="img\//g,
'background="'+m).replace(/url\('img\//g,"url('"+m);/@media /.test(b)&&(b=b.replace(/@media only screen and \(max-device-width: ?480/g,"@media only screen and (max-width: 599").replace(/@media only screen and \(max-device-width: ?320/g,"@media only screen and (max-width: 479"));a.document.body.innerHTML=b;$.browser.msie&&a.document.write(b)},500);return!1});$("#downloadbtn").bind("click",function(){if(g())return!1;g(!0);k("prepare download...");var a=n.val();r("download",{data:a},function(a){g(!1);
a.success&&window.open("proxy.php?download="+a.file)})});$("#mc_upload").bind("click",function(){if(g())return!1;if(!b.elements.length)return $("#step1").click(),k("You have to select at least one module!",!1),!1;g(!0);k("upload to Mailchimp...");var a={apikey:b.apikey,templatename:b.templatename,data:n.val()};r("upload_mc",a,function(a){g(!1)})});$("#cm_upload").bind("click",function(){if(g())return!1;if(!b.elements.length)return $("#step1").click(),k("You have to select at least one module!",!1),
!1;g(!0);k("upload to Campaign Monitor...");var a={apikey:b.apikey,templatename:b.templatename,clientid:b.clientid,data:n.val()};r("upload_cm",a,function(a){g(!1)})});$("#selectHTML").bind("click",function(){n.select().focus();setTimeout(function(){n[0].scrollTop=0},1)})})();J();y.find("a[data-version="+b.version+"]").parent().click();x(0);(function(){var a=localStorage.getItem(location.pathname+"settings");a&&(a=$.parseJSON(a),$.each(a,function(b,c){switch(b){case "version":$("#versions").find("li").eq(c-
1).click();break;case "color":B.val(c);break;case "service":$("a[data-role="+c+"]").click();break;case "apikey":switch(a.service){case "mc":$("#mc_apikey").val(c).trigger("change");break;case "cm":$("#cm_apikey").val(c).trigger("change")}break;case "inline":s.prop("checked",c);break;case "imagepath":v.val(c);break;case "preheader":A.val(c);break;case "absoluteurls":l.prop("checked",c);break;case "useeditor":$("#cm_useeditor").prop("checked",c);break;case "templatename":switch(a.service){case "mc":$("#mc_templatename").val(c);
break;case "cm":$("#cm_templatename").val(c)}}}),k("settings loaded"),b=a)})();$("[title]").tipsy({gravity:"s",opacity:1})};R()});
